apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
  labels:
    env: production
    tier: database
    app: configmap
    name: mysql-configmap
data:
  mysql-user: "msaportal"
  mysql-database: "msaportal"
  mysql-allow-empty-password: "1"
  mysql-root-host: "%"
  TZ: Asia/Seoul
  master.cnf: |
    [mysqld]
    log-bin
    character-set-server=utf8
    collation-server=utf8_general_ci
  slave.cnf: |
    [mysqld]
    super-read-only
    character-set-server=utf8
    collation-server=utf8_general_ci