apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    env: production
    tier: backend
    app: rabbitmq
    name: rabbitmq-service
spec:
  type: NodePort
  selector:
    env: production
    tier: backend
    app: rabbitmq
    name: rabbitmq-pod
  ports:
    - name: http-5672
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30003
    - name: http-15672
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 30004