apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apigateway-hpa-cpu
  labels:
    env: production
    tier: backend
    app: apigateway
    name: apigateway-hpa-cpu
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apigateway-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70